/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author vyngo
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Product product;
    public CreateJPanel(Product p) {
        initComponents();
        product = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblAvailNum = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldDescript = new javax.swing.JTextField();
        fieldAvailNum = new javax.swing.JTextField();
        fieldPrice = new javax.swing.JTextField();
        lblManufactureAddress = new javax.swing.JLabel();
        lblShippingAddress = new javax.swing.JLabel();
        lblManuStreetName = new javax.swing.JLabel();
        lblManuUnitNumber = new javax.swing.JLabel();
        lblManuCity = new javax.swing.JLabel();
        lblManuZipCode = new javax.swing.JLabel();
        fieldManuStreetName = new javax.swing.JTextField();
        fieldManuUnitNumber = new javax.swing.JTextField();
        fieldManuCity = new javax.swing.JTextField();
        fieldManuZipCode = new javax.swing.JTextField();
        lblShippingStreetName = new javax.swing.JLabel();
        lblShippingUnit = new javax.swing.JLabel();
        lblShippingCity = new javax.swing.JLabel();
        lblShippingZipCode = new javax.swing.JLabel();
        fieldShippingStreet = new javax.swing.JTextField();
        fieldShippingUnitNumber = new javax.swing.JTextField();
        fieldShippingCity = new javax.swing.JTextField();
        fieldShippingZipCode = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle.setText("Create a Product");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 35, 220, 50));

        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        lblDescription.setText("description");
        add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 167, 80, 20));

        lblAvailNum.setText("availNum");
        add(lblAvailNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 70, 20));

        lblPrice.setText("price");
        add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 30));

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 120, -1));
        add(fieldDescript, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 120, -1));
        add(fieldAvailNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 120, -1));
        add(fieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 120, -1));

        lblManufactureAddress.setText("manufacture address");
        add(lblManufactureAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        lblShippingAddress.setText("shipping address");
        add(lblShippingAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 120, -1));

        lblManuStreetName.setText("Street Name");
        add(lblManuStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        lblManuUnitNumber.setText("Unit Number");
        add(lblManuUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        lblManuCity.setText("City");
        add(lblManuCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        lblManuZipCode.setText("Zip Code");
        add(lblManuZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));
        add(fieldManuStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 80, -1));
        add(fieldManuUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 80, -1));

        fieldManuCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManuCityActionPerformed(evt);
            }
        });
        add(fieldManuCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 80, -1));
        add(fieldManuZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 80, -1));

        lblShippingStreetName.setText("Street Name");
        add(lblShippingStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        lblShippingUnit.setText("Unit Number");
        add(lblShippingUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        lblShippingCity.setText("City");
        add(lblShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        lblShippingZipCode.setText("Zip Code");
        add(lblShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));
        add(fieldShippingStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 80, -1));

        fieldShippingUnitNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingUnitNumberActionPerformed(evt);
            }
        });
        add(fieldShippingUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 80, -1));
        add(fieldShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 80, -1));
        add(fieldShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 80, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldManuCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManuCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManuCityActionPerformed

    private void fieldShippingUnitNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingUnitNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingUnitNumberActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
         //step 1: collect information from user input
        String productName = fieldName.getText();
        String description = fieldDescript.getText();
        String availNum = fieldAvailNum.getText();
        String price = fieldPrice.getText();
        
        String manuStreet = fieldManuStreetName.getText();
        String manuUnit = fieldManuUnitNumber.getText();
        String manuCity = fieldManuCity.getText();
        String manuZipCode = fieldManuZipCode.getText();
        
        String shippingStreet = fieldShippingStreet.getText();
        String shippingUnit = fieldShippingUnitNumber.getText();
        String shippingCity =  fieldShippingCity.getText();
        String shippingZipCode = fieldShippingZipCode.getText();
                
        //step 2: put all those information into a product
        product.setNames(productName);
        product.setDescription(description);
        product.setAvailNum(availNum);
        product.setPrice(price);
        
        product.getManufactureAddress().setStreetName(manuStreet);
        product.getManufactureAddress().setUnitNum(manuUnit);
        product.getManufactureAddress().setCity(manuCity);
        product.getManufactureAddress().setZipCode(manuZipCode);
        
        product.getShippingAddress().setStreetName(shippingStreet);
        product.getShippingAddress().setUnitNum(shippingUnit);
        product.getShippingAddress().setCity(shippingCity);
        product.getShippingAddress().setZipCode(shippingZipCode);
        
        //step 3: give a pop-up message
        JOptionPane.showMessageDialog(this, "Successfully Saved!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        //step 4: clear all text from textfield
        fieldName.setText("");
        fieldDescript.setText("");
        fieldAvailNum.setText("");
        fieldPrice.setText("");
        fieldManuStreetName.setText("");
        fieldManuUnitNumber.setText("");
        fieldManuCity.setText("");
        fieldManuZipCode.setText("");
        fieldShippingStreet.setText("");
        fieldShippingUnitNumber.setText("");
        fieldShippingCity.setText("");
        fieldShippingZipCode.setText("");
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAvailNum;
    private javax.swing.JTextField fieldDescript;
    private javax.swing.JTextField fieldManuCity;
    private javax.swing.JTextField fieldManuStreetName;
    private javax.swing.JTextField fieldManuUnitNumber;
    private javax.swing.JTextField fieldManuZipCode;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField fieldShippingCity;
    private javax.swing.JTextField fieldShippingStreet;
    private javax.swing.JTextField fieldShippingUnitNumber;
    private javax.swing.JTextField fieldShippingZipCode;
    private javax.swing.JLabel lblAvailNum;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblManuCity;
    private javax.swing.JLabel lblManuStreetName;
    private javax.swing.JLabel lblManuUnitNumber;
    private javax.swing.JLabel lblManuZipCode;
    private javax.swing.JLabel lblManufactureAddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblShippingAddress;
    private javax.swing.JLabel lblShippingCity;
    private javax.swing.JLabel lblShippingStreetName;
    private javax.swing.JLabel lblShippingUnit;
    private javax.swing.JLabel lblShippingZipCode;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
